swagger: '2.0'
info:
  version: '1.0'
  title: E1
  description: 'API per inserire,modificare, visualizzare ed eliminare assignments dal nostro database.'
host: e1setrento.herokuapp.com
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
  

  
paths:
  '/addAssignment':
    x-summary: Add a new assignment
    post:
      description: 'Aggiungi assignment nel database.'
      summary: 'Add assignment in database'
      parameters: 
        - name: Assignment
          in: body
          description: Assignment to add in database
          required: true
          "schema": {
              "$ref": "#/definitions/Assignment"
          }
      produces:
        - application/json
      responses:
        '200':
          description: ''
          schema:
            type: string
          examples:
            application/json: |-
              [
                  {
                      "taskID": "rhw57f8b2if72bnf7bnbdu",
                      "assignmentID": "Mario",
                      "workerID": "Rossi"
                      "assignmentResult": {\"vero\": "true",\"ciao\": 3}
                  }
              ]
  
  '/getAssignment':
    x-summary: Add a new assignment
    get:
      description: 'Obtain information about an assignments'
      summary: 'Obtain a list of assignments'
      produces:
        - application/json
      responses:
        '200':
          description: ''
          schema:
            type: object
          examples: 
            application/json: |-
              [
                  {
                      "taskID": "gsdgfds",
                      "assignmentID": "nhfjytmnjr",
                      "workerID": "jgm,kytgmfnsf"
                      "assignmentResult": {\"vero\": "true",\"ciao\": 3}
                  }
              ]
        '404':
          description: ''
          schema:
            type: object
          examples: 
            application/json: |-
              Not Found
  
"definitions": {
    "Assignment": {
      "type": "object",
      "properties": {
        "taskID": {
          "type": "string",
          "description": "taskID of assignment"
        },"assignmentID": {
          "type": "string",
          "description": "assignmentID of assignment"
        },
        "workerID": {
          "type": "string",
          "description": "workerID of assignment"
        },
        "assignmentResult ": {
          "type": "object",
          "description": "assignmentResult of assignment"
        }
    }
  }
}